import { Resend } from 'resend';
import db from '../database/connection';
// @ts-ignore - uuid v9 type issue
import { v4 as uuidv4 } from 'uuid';
import dotenv from 'dotenv';

dotenv.config();

export class EmailSender {
  private resend: Resend;
  private emailFrom: string;
  private emailTo: string;
  private dryRun: boolean;

  constructor() {
    this.resend = new Resend(process.env.RESEND_API_KEY);
    this.emailFrom = process.env.EMAIL_FROM || 'noreply@example.com';
    this.emailTo = process.env.EMAIL_TO || 'user@example.com';
    this.dryRun = process.env.DRY_RUN_EMAIL === 'true';
  }

  async sendDailySummary(
    summaries: { topicName: string; content: string }[],
    date: Date
  ): Promise<boolean> {
    try {
      const html = this.buildEmailHTML(summaries, date);
      const subject = this.buildEmailSubject(date);

      if (this.dryRun) {
        console.log('[DRY RUN] Would send email:');
        console.log(`  To: ${this.emailTo}`);
        console.log(`  Subject: ${subject}`);
        console.log(`  HTML Preview: ${html.substring(0, 200)}...`);

        // Still log the attempt
        const logId = uuidv4();
        await this.logEmailAttempt(logId, this.emailTo, subject, 'sent', null, []);
        return true;
      }

      const response = await this.resend.emails.send({
        from: this.emailFrom,
        to: this.emailTo,
        subject: subject,
        html: html,
      });

      // Handle Resend response (v3+ returns data directly, older versions nested)
      const emailId = (response as any).id || (response as any).data?.id;
      if (!emailId) {
        throw new Error('Failed to send email: No message ID returned');
      }

      // Log successful send
      const logId = uuidv4();
      await this.logEmailAttempt(logId, this.emailTo, subject, 'sent', null, []);

      console.log(`Email sent successfully: ${emailId}`);
      return true;
    } catch (error) {
      console.error('Error sending email:', error);

      // Log failed attempt
      const logId = uuidv4();
      await this.logEmailAttempt(
        logId,
        this.emailTo,
        this.buildEmailSubject(date),
        'failed',
        error instanceof Error ? error.message : String(error),
        []
      );

      return false;
    }
  }

  private buildEmailHTML(
    summaries: { topicName: string; content: string }[],
    date: Date
  ): string {
    const dateStr = date.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const summaryHtml = summaries.length === 0
      ? `
      <section style="margin-bottom: 30px; border-left: 4px solid #f59e0b; padding-left: 20px;">
        <h2 style="color: #1f2937; margin-top: 0; font-size: 20px;">No summary available</h2>
        <div style="color: #4b5563; line-height: 1.6; font-size: 14px;">
          No summaries were generated for today. This usually means the summarization
          step failed (e.g. a missing or invalid GEMINI_API_KEY) or no news was collected.
          Check the latest job logs.
        </div>
      </section>
    `
      : summaries
      .map(
        (summary) => `
      <section style="margin-bottom: 30px; border-left: 4px solid #3b82f6; padding-left: 20px;">
        <h2 style="color: #1f2937; margin-top: 0; font-size: 20px;">${summary.topicName}</h2>
        <div style="color: #4b5563; line-height: 1.6; font-size: 14px;">
          ${this.escapeHtml(summary.content).replace(/\n/g, '<br />')}
        </div>
      </section>
    `
      )
      .join('');

    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f3f4f6; padding: 20px;">
          <div style="max-width: 600px; margin: 0 auto; background-color: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
            <!-- Header -->
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px 20px; text-align: center; border-radius: 8px 8px 0 0;">
              <h1 style="color: white; margin: 0; font-size: 28px;">Jojo's News Digest</h1>
              <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0; font-size: 14px;">${dateStr}</p>
            </div>

            <!-- Content -->
            <div style="padding: 30px 20px;">
              <p style="color: #6b7280; margin-bottom: 20px;">
                Here's your daily curated news summary, automatically generated from multiple sources.
              </p>

              ${summaryHtml}

              <!-- Footer -->
              <div style="border-top: 1px solid #e5e7eb; margin-top: 30px; padding-top: 20px; font-size: 12px; color: #9ca3af;">
                <p>This email was automatically generated by Jojo's News Aggregator.</p>
                <p><a href="#" style="color: #3b82f6; text-decoration: none;">Manage preferences</a> | <a href="#" style="color: #3b82f6; text-decoration: none;">View in browser</a></p>
              </div>
            </div>
          </div>
        </body>
      </html>
    `;
  }

  private buildEmailSubject(date: Date): string {
    const dayName = date.toLocaleDateString('en-US', { weekday: 'long' });
    const dateStr = date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    return `Jojo's News Digest - ${dayName}, ${dateStr}`;
  }

  private escapeHtml(text: string): string {
    const map: { [key: string]: string } = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;',
    };
    return text.replace(/[&<>"']/g, (m) => map[m]);
  }

  private async logEmailAttempt(
    id: string,
    recipient: string,
    subject: string,
    status: 'sent' | 'failed',
    error: string | null,
    summaryIds: string[]
  ): Promise<void> {
    const query = `
      INSERT INTO email_logs (id, date, recipient, subject, status, sent_at, error, summary_ids)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    `;

    await db.execute(query, [
      id,
      new Date(),
      recipient,
      subject,
      status,
      status === 'sent' ? new Date() : null,
      error,
      summaryIds,
    ]);
  }
}

export default new EmailSender();
